version: '3'
services: 
    python:
        # image: python:3.7.7
        build: 
            context: .
            dockerfile: docker/python/Dockerfile
        volumes: 
            - ./:/app
        ports: 
            - 8000:8000
        # command: sleep infinity
        # command: cd app && sh ./install.sh
        
